"""Catalogs: tipos de norma and dependencias (organismos), with fuzzy lookup.

The JSON files are regenerated by ``scripts/update_configs.py`` from the live
``mostrarBusquedaNormas.do`` form. Fuzzy search uses rapidfuzz (WRatio, cutoff 70)
and is accent-insensitive.
"""

from __future__ import annotations

import json
import unicodedata
from pathlib import Path

from rapidfuzz import fuzz, process


def _normalize(text: str) -> str:
    text = (text or "").lower()
    return unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")


class CatalogService:
    def __init__(self, dependencias_path: str | Path, tipos_path: str | Path):
        self.dependencias_path = Path(dependencias_path)
        self.tipos_path = Path(tipos_path)
        self._deps: list[dict] | None = None
        self._tipos: list[dict] | None = None

    # ── loading ──────────────────────────────────────────────────────────────
    @staticmethod
    def _load(path: Path) -> list[dict]:
        if path.exists():
            try:
                return json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                return []
        return []

    @property
    def dependencias(self) -> list[dict]:
        if self._deps is None:
            self._deps = self._load(self.dependencias_path)
        return self._deps

    @property
    def tipos(self) -> list[dict]:
        if self._tipos is None:
            self._tipos = self._load(self.tipos_path)
        return self._tipos

    # ── dependencias ─────────────────────────────────────────────────────────
    def buscar_dependencias(self, query: str, limit: int = 10) -> list[dict]:
        deps = self.dependencias
        if not deps:
            return []
        choices = {i: _normalize(d["nombre"]) for i, d in enumerate(deps)}
        matches = process.extract(
            _normalize(query), choices, scorer=fuzz.WRatio, limit=limit, score_cutoff=70
        )
        return [{**deps[i], "score": round(score, 1)} for _, score, i in matches]

    def get_dependencia_by_id(self, dep_id: int) -> dict | None:
        return next((d for d in self.dependencias if d.get("id") == dep_id), None)

    def dependencia_nombre(self, dep_id: int) -> str | None:
        d = self.get_dependencia_by_id(dep_id)
        return d.get("nombre") if d else None

    # ── tipos ──────────────────────────────────────────────────────────────--
    def get_tipo_by_id(self, tipo_id: int) -> dict | None:
        return next((t for t in self.tipos if t.get("id") == tipo_id), None)

    def tipo_nombre(self, tipo_id: int) -> str | None:
        t = self.get_tipo_by_id(tipo_id)
        return t.get("nombre") if t else None

    def tipo_id(self, nombre: str) -> int | None:
        n = _normalize(nombre)
        return next((t["id"] for t in self.tipos if _normalize(t["nombre"]) == n), None)
